rax:
  api_username: test
  api_key: 123abc
  domains:
    - test.com
    - www.test.com

namecheap:
  test.com:
    hostname: www
    password: password

  example.com:
    hostname: test
    password: 123456